"""
Full 13-question multi-model Anti-Delphi batch.
4 combos × 13 questions = 52 runs.
Reads existing batch_results/ (single-agent) and
batch_results_antidelphi/ (single-model AD) as baselines.
"""

import subprocess
import json
import os
import shutil
import time
from pathlib import Path

QUESTIONS = {
    "A1": "Does raising the minimum wage increase unemployment?",
    "A2": "Is foreign aid effective at reducing poverty?",
    "A3": "Does immigration reduce wages for native workers?",
    "B1": "Is GDP a good measure of economic wellbeing?",
    "B2": "Is remote work more productive than office work?",
    "B3": "Is social media harmful to democracy?",
    "C1": "Is technology good?",
    "C2": "Is globalization beneficial?",
    "D1": "Is intermittent fasting effective for long-term weight loss?",
    "D2": "Does class size reduction improve educational outcomes?",
    "D3": "Is gene editing ethically justifiable in humans?",
    "E1": "Is free trade both beneficial and harmful to developing economies?",
    "E2": "Is economic growth compatible with ecological sustainability?",
}

COMBOS = [
    ("DS4_DS4",   "deepseek",    "deepseek-chat",                 "deepseek",   "deepseek-chat"),
    ("DS4_GPT4o", "deepseek",    "deepseek-chat",                 "openrouter", "openai/gpt-4o"),
    ("GPT4o_DS4", "openrouter",  "openai/gpt-4o",                 "deepseek",   "deepseek-chat"),
    ("Claude_Cl", "openrouter",  "anthropic/claude-sonnet-4-5",   "openrouter", "anthropic/claude-sonnet-4-5"),
]

RESULTS_DIR = Path("batch_results_multimodel")
RESULTS_DIR.mkdir(exist_ok=True)


# ---------------------------------------------------------------------------
# Extended metric helpers
# ---------------------------------------------------------------------------

def classify_topology(claims: dict, transitions: list[str]) -> str:
    t1 = "T1" in transitions
    t2 = "T2" in transitions
    t4 = "T4" in transitions
    t9 = "T9" in transitions
    if t1 and t9:
        return "contested"
    elif t2 and not t1:
        return "T2_path"
    elif t4 and not t1:
        return "branched"
    else:
        return "linear"


def avg_synthesis_confidence(claims: dict) -> float:
    synth = [c["confidence"] for c in claims.values() if c.get("is_synthesis")]
    return round(sum(synth) / len(synth), 3) if synth else 0.0


def count_branch_levels(claims: dict) -> int:
    return sum(1 for c in claims.values() if c.get("branch_open"))


def count_role_triggers(claims: dict, op_history: list[str]) -> tuple[int, int]:
    """Return (builder_t1_triggers, falsifier_t1_triggers).

    A T1 trigger is attributed to a role if the claim that caused T1 was
    generated by that role (determined via generated_by field).
    """
    builder = 0
    falsifier = 0
    # Build map: claim_id → generated_by
    gb_map = {cid: c.get("generated_by", "") for cid, c in claims.items()}
    for op in op_history:
        if op.startswith("T1 on "):
            parent_id = op.split("T1 on ")[-1].strip()
            # T1 fires on a claim whose counter was generated by a role
            # Look for the most recent T5[role] op that references parent_id
            pass
    # Simpler: count role claims that triggered contradiction (status=contradicted parent)
    for cid, c in claims.items():
        gb = c.get("generated_by", "")
        if not gb:
            continue
        pid = c.get("parent_id")
        if pid and claims.get(pid, {}).get("status") == "contradicted":
            if "[hypothesis_builder]" in gb:
                builder += 1
            elif "[falsifier]" in gb:
                falsifier += 1
    return builder, falsifier


# ---------------------------------------------------------------------------
# Single run
# ---------------------------------------------------------------------------

def run_single(combo_id: str, bp: str, bm: str, fp: str, fm: str,
               qid: str, question: str) -> dict:
    print(f"\n{'='*70}")
    print(f"Running {combo_id} / {qid}: builder={bm} | falsifier={fm}")
    print(f"  Q: {question}")
    print("=" * 70)

    subprocess.run(["python", "des.py", "--reset"], capture_output=True, env=os.environ)

    cmd = [
        "python", "des.py", question,
        "--max-iter", "60",
        "--anti-delphi",
        "--builder-provider", bp,
        "--builder-model", bm,
        "--falsifier-provider", fp,
        "--falsifier-model", fm,
    ]
    start = time.time()
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=360, env=os.environ)
    elapsed = time.time() - start

    state_data = {}
    if Path("des_state.json").exists():
        with open("des_state.json") as f:
            state_data = json.load(f)

    claims = state_data.get("claims", {})
    op_history = state_data.get("operation_history", [])
    transitions_fired = sorted(set(
        op.split("[")[0].split(" ")[0]
        for op in op_history if op
    ))

    sealed_count    = sum(1 for c in claims.values() if c.get("sealed"))
    open_count      = sum(1 for c in claims.values() if not c.get("sealed"))
    role_count      = sum(1 for c in claims.values() if c.get("is_role_generated"))
    synthesis_count = sum(1 for c in claims.values() if c.get("is_synthesis"))

    generated_by_counts: dict[str, int] = {}
    for c in claims.values():
        gb = c.get("generated_by", "")
        if gb:
            generated_by_counts[gb] = generated_by_counts.get(gb, 0) + 1

    builder_t1, falsifier_t1 = count_role_triggers(claims, op_history)
    topology = classify_topology(claims, transitions_fired)
    synth_conf = avg_synthesis_confidence(claims)
    branch_depth = count_branch_levels(claims)

    result_data = {
        "combo_id": combo_id,
        "qid": qid,
        "question": question,
        "builder_provider": bp,
        "builder_model": bm,
        "falsifier_provider": fp,
        "falsifier_model": fm,
        "success": result.returncode == 0,
        "elapsed_seconds": round(elapsed, 1),
        "iterations": state_data.get("iteration", 0),
        "claims_total": len(claims),
        "claims_sealed": sealed_count,
        "claims_open": open_count,
        "claims_synthesis": synthesis_count,
        "claims_role_generated": role_count,
        "generated_by_counts": generated_by_counts,
        "transitions_fired": transitions_fired,
        "t1_fired": "T1" in transitions_fired,
        "t2_fired": "T2" in transitions_fired,
        "t9_fired": "T9" in transitions_fired,
        "reframing_count": state_data.get("reframing_count", 0),
        "anti_delphi_activations": state_data.get("anti_delphi_activations", 0),
        "topology": topology,
        "contradiction_depth": branch_depth,
        "synthesis_confidence": synth_conf,
        "builder_t1_trigger": builder_t1,
        "falsifier_t1_trigger": falsifier_t1,
        "error": result.stderr[-500:] if result.returncode != 0 else None,
        "stdout_tail": result.stdout[-800:],
    }

    run_key = f"{combo_id}_{qid}"
    with open(RESULTS_DIR / f"{run_key}.json", "w") as f:
        json.dump(result_data, f, indent=2)
    if Path("des_state.json").exists():
        shutil.copy("des_state.json", RESULTS_DIR / f"{run_key}_state.json")

    return result_data


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def print_summary(results: list[dict]):
    print("\n" + "=" * 100)
    print("MULTI-MODEL FULL BATCH SUMMARY")
    print("=" * 100)
    print(f"{'Combo':<12} {'Q':<4} {'OK':<4} {'Iter':<6} {'Claims':<7} {'Open':<5} "
          f"{'AD':<4} {'T1':<4} {'T2':<4} {'T9':<4} {'Topology':<12} {'SynthConf'}")
    print("-" * 100)

    for r in results:
        ok    = "YES" if r["success"] else "NO"
        t1    = "Y" if r["t1_fired"] else "-"
        t2    = "Y" if r["t2_fired"] else "-"
        t9    = "Y" if r["t9_fired"] else "-"
        ad    = str(r.get("anti_delphi_activations", 0))
        topo  = r.get("topology", "?")
        sc    = f"{r.get('synthesis_confidence', 0):.3f}"
        print(f"{r['combo_id']:<12} {r['qid']:<4} {ok:<4} "
              f"{r['iterations']:<6} {r['claims_total']:<7} {r['claims_open']:<5} "
              f"{ad:<4} {t1:<4} {t2:<4} {t9:<4} {topo:<12} {sc}")

    print("-" * 100)
    n = len(results)
    if n == 0:
        return

    success_rate = sum(1 for r in results if r["success"]) / n * 100
    t1_rate      = sum(1 for r in results if r["t1_fired"]) / n * 100
    t2_rate      = sum(1 for r in results if r["t2_fired"]) / n * 100
    t9_rate      = sum(1 for r in results if r["t9_fired"]) / n * 100
    avg_claims   = sum(r["claims_total"] for r in results) / n
    avg_iter     = sum(r["iterations"] for r in results) / n
    total_open   = sum(r["claims_open"] for r in results)

    print(f"\nSuccess rate:    {success_rate:.0f}%")
    print(f"T1 fire rate:    {t1_rate:.0f}%")
    print(f"T2 fire rate:    {t2_rate:.0f}%")
    print(f"T9 fire rate:    {t9_rate:.0f}%")
    print(f"Avg claims/run:  {avg_claims:.1f}")
    print(f"Avg iter/run:    {avg_iter:.1f}")
    print(f"Total open:      {total_open}")

    # Topology distribution
    from collections import Counter
    topo_counts = Counter(r["topology"] for r in results)
    print(f"\nTopology distribution ({n} runs):")
    for topo, cnt in sorted(topo_counts.items()):
        print(f"  {topo:<12} {cnt:>3}  ({cnt/n*100:.0f}%)")

    # Per-combo aggregate
    print("\n" + "=" * 80)
    print("PER-COMBO AGGREGATE")
    print("-" * 80)
    print(f"{'Combo':<12} {'Runs':<6} {'OK':<4} {'AvgClaims':<11} {'AvgIter':<10} "
          f"{'T1%':<6} {'T2%':<6} {'Topo(C/T2/B/L)'}")
    print("-" * 80)
    combos_seen = list(dict.fromkeys(r["combo_id"] for r in results))
    for cid in combos_seen:
        sub = [r for r in results if r["combo_id"] == cid]
        ns   = len(sub)
        ok_s = sum(1 for r in sub if r["success"])
        avg_c = sum(r["claims_total"] for r in sub) / ns
        avg_i = sum(r["iterations"] for r in sub) / ns
        t1p   = sum(r["t1_fired"] for r in sub) / ns * 100
        t2p   = sum(r["t2_fired"] for r in sub) / ns * 100
        tc    = Counter(r["topology"] for r in sub)
        tstr  = f"{tc.get('contested',0)}/{tc.get('T2_path',0)}/{tc.get('branched',0)}/{tc.get('linear',0)}"
        print(f"{cid:<12} {ns:<6} {ok_s:<4} {avg_c:<11.1f} {avg_i:<10.1f} "
              f"{t1p:<6.0f} {t2p:<6.0f} {tstr}")

    print("\nISSUES:")
    issues = False
    for r in results:
        if not r["success"]:
            print(f"  FAIL {r['combo_id']}/{r['qid']}: {str(r.get('error',''))[:120]}")
            issues = True
        if r["claims_open"] > 0:
            print(f"  OPEN {r['combo_id']}/{r['qid']}: {r['claims_open']} unsealed")
            issues = True
    if not issues:
        print("  None.")

    with open(RESULTS_DIR / "summary.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nFull results saved to: {RESULTS_DIR}/")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    results = []
    for combo_id, bp, bm, fp, fm in COMBOS:
        for qid, question in QUESTIONS.items():
            run_key = f"{combo_id}_{qid}"
            existing = RESULTS_DIR / f"{run_key}.json"
            if existing.exists():
                print(f"  [skip] {run_key} already exists")
                with open(existing) as f:
                    results.append(json.load(f))
                continue
            try:
                r = run_single(combo_id, bp, bm, fp, fm, qid, question)
                results.append(r)
                status = "OK" if r["success"] else "FAIL"
                print(f"  -> {status} | {r['iterations']} iter | "
                      f"{r['claims_total']} claims | open={r['claims_open']} "
                      f"AD={r.get('anti_delphi_activations', 0)} "
                      f"T1={r['t1_fired']} T2={r['t2_fired']} T9={r['t9_fired']} "
                      f"topo={r['topology']}")
            except subprocess.TimeoutExpired:
                print(f"  -> TIMEOUT after 360s")
                results.append({
                    "combo_id": combo_id, "qid": qid, "question": question,
                    "builder_provider": bp, "builder_model": bm,
                    "falsifier_provider": fp, "falsifier_model": fm,
                    "success": False, "error": "timeout",
                    "transitions_fired": [], "t1_fired": False, "t2_fired": False,
                    "t9_fired": False, "claims_total": 0, "claims_open": 0,
                    "claims_sealed": 0, "claims_synthesis": 0, "claims_role_generated": 0,
                    "generated_by_counts": {}, "iterations": 0, "reframing_count": 0,
                    "anti_delphi_activations": 0, "elapsed_seconds": 360,
                    "topology": "linear", "contradiction_depth": 0,
                    "synthesis_confidence": 0.0,
                    "builder_t1_trigger": 0, "falsifier_t1_trigger": 0,
                })
            except Exception as e:
                print(f"  -> ERROR: {e}")

    print_summary(results)
